### ISSUE TITLE
[4pt]  - Create feature: add new comment - Student B

### ISSUE THREAD

**Issue by Fatima-hub333** [Fatima-hub333/Capstone-Movies-Api#8]
Implement the "add new comment" form on the Comments pop up according to the wireframe:

<img width="360" alt="Screenshot 2021-06-27 at 22 32 36" src="https://user-images.githubusercontent.com/7466903/123558625-98e35180-d797-11eb-9607-8f294273ca01.png">

When the user clicks on the "Comment" button, the data is recorded in the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) and the screen is updated.

**Comment by amklass11** [comment]
Hi @Fatima-hub333 
> # Status: Approved ✔
> * No linter errors
> * Good code structure.
> 
> You have successfully applied the required changes. Nothing else remaining. It is time to merge. ![200](https://user-images.githubusercontent.com/99394374/170295830-022f3787-7be3-401f-b13a-1d2e7e611e88.gif)
